### ISSUE TITLE
Improving runtime performance (esp. on Apple Silicon)

### ISSUE THREAD

**Issue by humphd** [tamim662/Yolo-Fish#2]
I've been working with YOLO-fish to detect target species of minnows in videos, and I'm really pleased that this is possible.  This is amazing work, thank you for sharing it!

However, I have to run it on M1 Macs, and I'm finding it extremely slow for working with video.  I wonder if anyone has thoughts on getting this to run faster?  For example, are there any plans to update this to use yolov8 (which can use Apple's GPUs)?  I also tried using [this OpenCL version of Darknet](https://github.com/sowson/darknet), and it's better, but still slow.

Thanks for any insight or tips.

**Comment by humphd** [comment]
I was finally able to get this working, and thought I'd leave a note for anyone who wants to do the same.

In order to run this on MacOS more quickly, you want an ONNX model (none of the darknet-based implementations for Mac are efficient enough with this model--I've tried them all!).  You can use [pytorch-YOLOv4](https://github.com/Tianxiaomo/pytorch-YOLOv4) to create the ONNX model.  Doing so requires that you grab the [yolov4.cfg](https://github.com/tamim662/YOLO-Fish/blob/main/models/trained_on_merge/yolov4.cfg) and the `merge_yolo4.weights` file from [here](https://drive.google.com/drive/folders/1BmBdxwGCH3IS0kTeDxK2hT8vVvEtd_3o?usp=sharing) (i.e., files included/linked in this repo).  Next, make a file called `yolo-fish.names`, which is just the word `fish` with a newline:

```plaintext
fish

```

Now you're ready to do the conversion.  The script runs inference on your model, converting it to ONNX first.  You have to specify an image path and batch size (I've used `fish-image.jpg` and `1` below):

```sh
$ git clone git@github.com:Tianxiaomo/pytorch-YOLOv4.git
$ cd pytorch-YOLOv4
$ python demo_darknet2onnx.py path/to/yolov4.cfg path/to/yolo-fish.names path/to/merge_yolov4.weights fish-image.jpg 1
```

This will both work and fail.  First, you'll end-up with a new ONNX model file (mine is named `yolov4_1_3_608_608_static.onnx`).  This is what you need in order to run things with ONNX runtimes.

The code in `demo_darknet2onnx.py` tha draws the bounding boxes is broken (use `int()` for the values passed to `rectangle()` instead of using floats like they do now:

```python
            cv2.rectangle(img, (x1,y1), (int(c3[0]), int(c3[1])), rgb, -1)
            img = cv2.putText(img, msg, (c1[0], int(c1[1] - 2)), cv2.FONT_HERSHEY_SIMPLEX,0.7, (0,0,0), bbox_thick//2,lineType=cv2.LINE_AA)
```

The code in https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/master/demo_darknet2onnx.py is a useful example of what you need to do in order to run inference on the ONNX model.  You can strip out the conversion code, and keep the bit that does detection, etc.

I tried using [onnxruntime-silicon](https://github.com/cansik/onnxruntime-silicon) so I could use CoreML, but it fails with `CoreML does not support input dim > 16384`, which I haven't had time to dig into.  However, even running this on my M1 CPU has gone from being things being accurate but too slow to be useful, to running fast enough to build other things on top of, which is my next task!

If others have better suggestions about how to improve on what I've done above, please let me know.

Thanks to the creators of YOLO-fish, it's an excellent starting point for our work.

**Comment by tamim662** [comment]
improvement disclosed.
